name: Convert and Validate SVG to XML and YAML

on:
  push:
    branches-ignore:
      - main

jobs:
  convert-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean Workspace
        run: |
          make clean

      - name: Convert SVG to XML
        run: |
          make convert-drawio-svg-to-xml

      - name: Convert XML to Backstage YAML
        run: |
          make convert-xml-to-backstage-files

      - name: Validate XML and YAML Files
        run: |
          SVG_DIR="docs/design/drawio"
          XML_DIR="docs/design/xml"
          CATALOG_DIR="catalog"

          if [ -z "$(ls -A "$SVG_DIR"/*.svg 2>/dev/null)" ]; then
            echo "No SVG files found in $SVG_DIR"
            exit 1
          fi
          # Validate each SVG has a corresponding XML
          for svg_file in "$SVG_DIR"/*.svg; do
            base_name=$(basename "$svg_file" .svg)
            xml_file="$XML_DIR/$base_name.xml"
            if [ ! -f "$xml_file" ]; then
              echo "Error: XML file $xml_file does not exist for $svg_file"
              exit 1
            fi
            if [ ! -s "$xml_file" ]; then
              echo "Error: XML file $xml_file is empty"
              exit 1
            fi
          done
          # Validate catalog files exist
          for dir in "$CATALOG_DIR"/system "$CATALOG_DIR"/container "$CATALOG_DIR"/component; do
            if [ ! -f "$dir/catalog-info.yaml" ]; then
              echo "Error: catalog-info.yaml not found in $dir"
              exit 1
            fi
            if [ ! -s "$dir/catalog-info.yaml" ]; then
              echo "Error: catalog-info.yaml in $dir is empty"
              exit 1
            fi
          done
          echo "Validation successful: All XML and YAML files are present and non-empty"
